name: Ubuntu Terminal with Persistent Storage, Docker, Tailscale
on:
  workflow_dispatch:

jobs:
  ubuntu-terminal:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    steps:
      - name: Create SSH User
        run: |
          PASSWORD=$(tr -dc 'A-Za-z0-9!@#$%^&*()-_=+' < /dev/urandom | head -c20)
          echo "SSH_PASSWORD=$PASSWORD" >> $GITHUB_ENV

          sudo useradd -m -s /bin/bash rdpuser
          echo "rdpuser:$PASSWORD" | sudo chpasswd
          sudo usermod -aG sudo rdpuser

          sudo apt-get update
          sudo apt-get install -y openssh-server
          sudo systemctl enable ssh
          sudo systemctl start ssh

      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com | sh
          sudo usermod -aG docker rdpuser
          docker --version

      - name: Prepare Local Storage Folder
        run: |
          sudo mkdir -p /mnt/storage
          sudo chown rdpuser:rdpuser /mnt/storage

      - name: Install rclone and Configure
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          S3_REGION: ${{ secrets.S3_REGION }}
        run: |
          curl -O https://downloads.rclone.org/rclone-current-linux-amd64.deb
          sudo apt install -y ./rclone-current-linux-amd64.deb

          # Write config directly for rdpuser
          sudo -u rdpuser mkdir -p /home/rdpuser/.config/rclone
          cat <<EOF | sudo tee /home/rdpuser/.config/rclone/rclone.conf
          [s3-storage]
          type = s3
          provider = AWS
          access_key_id = $AWS_ACCESS_KEY_ID
          secret_access_key = $AWS_SECRET_ACCESS_KEY
          region = $S3_REGION
          EOF
          sudo chown -R rdpuser:rdpuser /home/rdpuser/.config

          # Sync from S3 to local
          rclone --config=/home/rdpuser/.config/rclone/rclone.conf sync s3-storage:$S3_BUCKET_NAME /mnt/storage
          echo "S3 data synced to /mnt/storage"

          # Add alias for easy push
          echo 'alias s3push="rclone --config=/home/rdpuser/.config/rclone/rclone.conf sync /mnt/storage s3-storage:'$S3_BUCKET_NAME'"' | sudo tee -a /home/rdpuser/.bashrc

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Start Tailscale (with SSH enabled)
        run: |
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --ssh --hostname=gh-ubuntu-${GITHUB_RUN_ID}
          TS_IP=$(tailscale ip -4 | head -n1)
          echo "TAILSCALE_IP=$TS_IP" >> $GITHUB_ENV

      - name: Verify SSH
        run: |
          echo "Tailscale IP: $TAILSCALE_IP"
          nc -zv $TAILSCALE_IP 22 || (echo "SSH not reachable" && exit 1)

      - name: Keep Alive
        run: |
          echo -e "\n=== SSH Access Details ==="
          echo "Address: $TAILSCALE_IP"
          echo "Username: rdpuser"
          echo "Password: $SSH_PASSWORD"
          echo "Persistent Storage: /mnt/storage"
          echo "Docker Installed ✔️"
          echo "To sync data back to S3: run 's3push' inside your SSH session"
          echo "===========================\n"

          while true; do
            echo "[$(date)] Ubuntu SSH session active..."
            sleep 60
          done

      - name: Sync Back to S3 (on exit)
        if: always()
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          echo "Syncing local changes back to S3..."
          rclone --config=/home/rdpuser/.config/rclone/rclone.conf sync /mnt/storage s3-storage:$S3_BUCKET_NAME

